# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N9bCw5pqDOhHPvzSMKpayiXpVLPlbSGw
"""

### Import required libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""#### Read the original dataset"""

titanic = pd.read_csv("https://raw.githubusercontent.com/vamsivarma/datasets/master/data_science/pandas/titanic.csv")

"""#### Do basic data exploration using Pandas"""

# Understand the structure of dataset using head, we can also use tail method
# Head - first 5 rows of dataset
# Tail - last 5 rows of dataset
titanic.head()

titanic.shape

titanic.info()

"""#### so from this overview we understand that fields with more null values are age and deck

### Understand the structure or schema of dataset
"""

titanic.dtypes

"""### Understand the high level summary of dataset fields based on their datatype

### Summary of all numerical fields in the dataset
"""

titanic.describe(include = [np.number])

"""### Summary of all categorical fields in the dataset"""

titanic.describe(include = ['O'])

"""### Do basic visualization using Matplotlib

### Using Histogram to understand distribution of a particular column
"""

x = titanic['age']
plt.hist(x)
plt.show()

"""so we can observe from above distribution that lot of people are aged between 20 and 40 years

similarly we can understand the distribution of other fields like fare
"""

x = titanic['fare']
plt.hist(x)
plt.show()

"""#### Read the dataset after data preprocessing

### Using scatter charts to understand the correlation betweeen 2 fields

**Example**: age vs fare
"""

fig, ax = plt.subplots()
x = titanic['age']
y = titanic['fare']
ax.scatter(x, y)
plt.show()

"""### Using pie chart to understand the distribution in Categorical fields"""

titanic['embark_town'].value_counts().plot.pie()
plt.show()

titanic['class'].value_counts().plot.pie()
plt.show()

titanic['sex'].value_counts().plot.pie()
plt.show()

titanic['alive'].value_counts().plot.pie()
plt.show()

dir(plt)

"""### Identifying the outliers with box plots"""

titanic['age'].plot.box()
plt.show()

"""### Using Bar chart to understand correlation between 2 fields"""

#total_s = titanic.groupby(by=['embark_town'])['class'].sum()
#total_s
#total_s.plot.bar()
#plt.show()

"""### Correlation"""

corr_matrix = titanic.corr()
sns.heatmap(corr_matrix, annot=True)
plt.show()

"""### Using pair plot"""

#sns.pairplot(titanic)
#plt.show()

titanic.head()



"""#**Homeworks**

1) Try to fix the errors easily
"""